import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * Every plugin the app imports has to be in the Podfile, or it is not in the app.
 *
 * A Capacitor plugin is a JavaScript wrapper over a native pod. The wrapper
 * installs with `npm install` and the pod does not: the Podfile is generated,
 * and it is regenerated by `npx cap sync ios`. Add a plugin, forget the sync,
 * and everything still builds — the JS is there, the native half is not, and
 * the call fails at run time on the device with "not implemented".
 *
 * That had happened. The Podfile listed `CapacitorFilesystem` alone, while the
 * app had been importing `@capacitor/camera` and
 * `@capacitor/local-notifications` for several commits. The mirror would have
 * worked; the camera and every deadline alert — the whole reason this app has a
 * native build — would not.
 *
 * Nothing else could see it. The Podfile is read by CocoaPods, which needs a
 * Mac; no test here compiles anything, and `npm run ios` boots the web bundle
 * with the bridge stubbed, so a missing pod looks exactly like a browser.
 *
 * So this walks the REAL dependency list and the REAL podspec names out of
 * node_modules, rather than a list kept by hand — a list would have been
 * written on the day of the mistake and would have had the same gap in it.
 */
const ROOT = join(__dirname, '..');
const PODFILE = readFileSync(join(ROOT, 'ios', 'App', 'Podfile'), 'utf8');

/** `@capacitor/*` packages that are plugins — the runtime itself is not one. */
const NOT_PLUGINS = new Set(['core', 'cli', 'ios', 'android']);

const plugins = (): string[] =>
  Object.keys(JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).dependencies ?? {})
    .filter((name) => name.startsWith('@capacitor/'))
    .filter((name) => !NOT_PLUGINS.has(name.slice('@capacitor/'.length)));

/** The pod's real name, from the podspec the package ships. */
const podName = (pkg: string): string | null => {
  const dir = join(ROOT, 'node_modules', pkg);
  if (!existsSync(dir)) return null;
  const spec = readdirSync(dir).find((f) => f.endsWith('.podspec'));
  return spec ? spec.replace(/\.podspec$/, '') : null;
};

describe('the native half of every plugin', () => {
  it('finds the plugins it is meant to be checking', () => {
    // A sweep over an empty list passes silently, reporting success for a
    // question it never asked — and this one reads two files that could each
    // start returning nothing.
    expect(plugins().length).toBeGreaterThanOrEqual(2);
    for (const pkg of plugins()) expect(podName(pkg), `${pkg} ships no podspec`).toBeTruthy();
  });

  it('is declared in the Podfile', () => {
    const missing = plugins().filter((pkg) => !PODFILE.includes(`pod '${podName(pkg)}'`));
    expect(
      missing,
      `not in ios/App/Podfile: ${missing.join(', ')} — run \`npx cap sync ios\``,
    ).toEqual([]);
  });

  it('points at the package that is actually installed', () => {
    // A pod whose path is wrong fails `pod install` on the Mac rather than at
    // run time, which is better, but it is the same staleness and the same fix.
    for (const pkg of plugins()) {
      expect(PODFILE, `${podName(pkg)} does not point at ${pkg}`)
        .toContain(`pod '${podName(pkg)}', :path => '../../node_modules/${pkg}'`);
    }
  });

  it('declares no pod for a plugin that is no longer a dependency', () => {
    /*
     * The other direction, and it is not symmetric: a leftover pod names a
     * path into node_modules that `npm install` will not create, so
     * `pod install` fails outright on the machine doing the building.
     */
    const wanted = new Set(plugins().map(podName));
    const declared = [...PODFILE.matchAll(/pod '(Capacitor\w+)', :path => '\.\.\/\.\.\/node_modules\/@capacitor\/([\w-]+)'/g)]
      .filter(([, , pkg]) => !NOT_PLUGINS.has(pkg))
      .map(([, pod]) => pod);
    const stale = declared.filter((pod) => !wanted.has(pod));
    expect(stale, `declared but not a dependency: ${stale.join(', ')}`).toEqual([]);
  });
});
